# fly.toml app configuration file generated for text-to-audio-bot on 2025-10-30T14:05:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'text-to-audio-bot'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  NODE_ENV = "production"
  PORT = 3000
  APP_BASE_URL="https://text-to-audio-bot.fly.dev"

[processes]
  app = "node dist/index.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
